=== RadwaHuss/XMLAPI/message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="MyMsg" type="MyMsgType"/>
  <xs:complexType name="MsgType">
    <xs:sequence>
      <xs:element type="xs:string" name="from"/>
      <xs:element type="xs:string" name="to"/>
      <xs:element type="xs:date" name="date"/>
      <xs:element type="xs:string" name="body"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MyMsgType">
    <xs:sequence>
      <xs:element type="xs:string" name="Header"/>
      <xs:element type="MsgType" name="Msg" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== RadwaHuss/XMLAPI/message.xml
<?xml version="1.0" encoding="UTF-8"?>
<MyMsg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="message.xsd">
    <Header>Welcome To Jets</Header>
    <Msg>
        <from>Noura</from>
        <to>Adel</to>
        <date>2020-02-18</date>
        <body>Welcome Welcome</body>
    </Msg>
    <Msg>
        <from>Noura</from>
        <to>Ahmed</to>
        <date>2020-02-18</date>
        <body>delivery of lab2</body>
    </Msg>
</MyMsg>
